#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_03.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="prayers")]
	public partial class prayersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertprayer(prayer instance);
    partial void Updateprayer(prayer instance);
    partial void Deleteprayer(prayer instance);
    #endregion
		
		public prayersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["prayersConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public prayersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public prayersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public prayersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public prayersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<prayer> prayers
		{
			get
			{
				return this.GetTable<prayer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.prayers")]
	public partial class prayer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _majid_name;
		
		private string _masjid_area;
		
		private string _fajar_time;
		
		private string _zohar_time;
		
		private string _asar_time;
		
		private string _maghrib_time;
		
		private string _esha_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmajid_nameChanging(string value);
    partial void Onmajid_nameChanged();
    partial void Onmasjid_areaChanging(string value);
    partial void Onmasjid_areaChanged();
    partial void Onfajar_timeChanging(string value);
    partial void Onfajar_timeChanged();
    partial void Onzohar_timeChanging(string value);
    partial void Onzohar_timeChanged();
    partial void Onasar_timeChanging(string value);
    partial void Onasar_timeChanged();
    partial void Onmaghrib_timeChanging(string value);
    partial void Onmaghrib_timeChanged();
    partial void Onesha_timeChanging(string value);
    partial void Onesha_timeChanged();
    #endregion
		
		public prayer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_majid_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string majid_name
		{
			get
			{
				return this._majid_name;
			}
			set
			{
				if ((this._majid_name != value))
				{
					this.Onmajid_nameChanging(value);
					this.SendPropertyChanging();
					this._majid_name = value;
					this.SendPropertyChanged("majid_name");
					this.Onmajid_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masjid_area", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string masjid_area
		{
			get
			{
				return this._masjid_area;
			}
			set
			{
				if ((this._masjid_area != value))
				{
					this.Onmasjid_areaChanging(value);
					this.SendPropertyChanging();
					this._masjid_area = value;
					this.SendPropertyChanged("masjid_area");
					this.Onmasjid_areaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fajar_time", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fajar_time
		{
			get
			{
				return this._fajar_time;
			}
			set
			{
				if ((this._fajar_time != value))
				{
					this.Onfajar_timeChanging(value);
					this.SendPropertyChanging();
					this._fajar_time = value;
					this.SendPropertyChanged("fajar_time");
					this.Onfajar_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zohar_time", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string zohar_time
		{
			get
			{
				return this._zohar_time;
			}
			set
			{
				if ((this._zohar_time != value))
				{
					this.Onzohar_timeChanging(value);
					this.SendPropertyChanging();
					this._zohar_time = value;
					this.SendPropertyChanged("zohar_time");
					this.Onzohar_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asar_time", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string asar_time
		{
			get
			{
				return this._asar_time;
			}
			set
			{
				if ((this._asar_time != value))
				{
					this.Onasar_timeChanging(value);
					this.SendPropertyChanging();
					this._asar_time = value;
					this.SendPropertyChanged("asar_time");
					this.Onasar_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maghrib_time", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maghrib_time
		{
			get
			{
				return this._maghrib_time;
			}
			set
			{
				if ((this._maghrib_time != value))
				{
					this.Onmaghrib_timeChanging(value);
					this.SendPropertyChanging();
					this._maghrib_time = value;
					this.SendPropertyChanged("maghrib_time");
					this.Onmaghrib_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esha_time", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string esha_time
		{
			get
			{
				return this._esha_time;
			}
			set
			{
				if ((this._esha_time != value))
				{
					this.Onesha_timeChanging(value);
					this.SendPropertyChanging();
					this._esha_time = value;
					this.SendPropertyChanged("esha_time");
					this.Onesha_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
